
import { API_URL } from '../services/app-config';

export let employeeUrl = {
  employee: {
    add: API_URL + "employee/add",
    update: API_URL + "employee/update",
    list: API_URL + "employee/list",
    listActive: API_URL + "employee/list-active",
    chart: API_URL + "employee/chart-generator",
    get: API_URL + "employee/get/",
    get2: API_URL + "employee/get2/",
    supervisors: API_URL + "employee/supervisors",
    evaluators: API_URL + "employee/evaluators",
    relievers: API_URL + "employee/relievers",
    employeeProfile: API_URL + "employee/employeeProfile",
    changePassword: API_URL + "employee/changePassword",
    summary: API_URL + "employee/summary",
    employeeInfo: API_URL + "employee/employeeInfo/",
    resetPassword: API_URL + "employee2/resetPassword",
    resetPassword2: API_URL + "employee2/resetPassword2",
    promptUpdate: API_URL + "employee/promptUpdate",
  },
  employeedependent: {
    add: API_URL + "employeedependent/add",
    update: API_URL + "employeedependent/update",
    list: API_URL + "employeedependent/list",
    get: API_URL + "employeedependent/get",
    getbyempid: API_URL + "employeedependent/getbyempid/",
  },
  employeedeployment: {
    add: API_URL + "employeedeployment/add",
    update: API_URL + "employeedeployment/update",
    list: API_URL + "employeedeployment/list",
    get: API_URL + "employeedeployment/get",
  },
  employeedesignation: {
    add: API_URL + "employeedesignation/add",
    update: API_URL + "employeedesignation/update",
    list: API_URL + "employeedesignation/list",
    get: API_URL + "employeedesignation/get",
  },
  employeeeducation: {
    add: API_URL + "employeeeducation/add",
    update: API_URL + "employeeeducation/update",
    list: API_URL + "employeeeducation/list",
    get: API_URL + "employeeeducation/get/",
    getbyempid: API_URL + "employeeeducation/getbyempid/",
  },
  employeefamily: {
    add: API_URL + "employeefamily/add",
    update: API_URL + "employeefamily/update",
    list: API_URL + "employeefamily/list",
    get: API_URL + "employeefamily/get/",
    getbyempid: API_URL + "employeefamily/getbyempid/",
  },
  employeeguarantor: {
    add: API_URL + "employeeguarantor/add",
    update: API_URL + "employeeguarantor/update",
    list: API_URL + "employeeguarantor/list",
    get: API_URL + "employeeguarantor/get/",
    getbyempid: API_URL + "employeeguarantor/getbyempid/",
  },
  employeereward: {
    add: API_URL + "employeereward/add",
    update: API_URL + "employeereward/update",
    list: API_URL + "employeereward/list",
    get: API_URL + "employeereward/get",
  },
  employeetitle: {
    add: API_URL + "employeetitle/add",
    update: API_URL + "employeetitle/update",
    list: API_URL + "employeetitle/list",
    get: API_URL + "employeetitle/get",
  },
  employeetype: {
    add: API_URL + "employeetype/add",
    update: API_URL + "employeetype/update",
    list: API_URL + "employeetype/list",
    get: API_URL + "employeetype/get",
  },
  offence: {
    add: API_URL + "offence/add",
    update: API_URL + "offence/update",
    list: API_URL + "offence/list",
    get: API_URL + "offence/get",
  },
  relationship: {
    add: API_URL + "relationship/add",
    update: API_URL + "relationship/update",
    list: API_URL + "relationship/list",
    get: API_URL + "relationship/get",
  },
  reward: {
    add: API_URL + "reward/add",
    update: API_URL + "reward/update",
    list: API_URL + "reward/list",
    get: API_URL + "reward/get",
  },
  employeesanction: {
    add: API_URL + "employeesanction/add",
    update: API_URL + "employeesanction/update",
    list: API_URL + "employeesanction/list",
    get: API_URL + "employeesanction/get",
  },
  sanction: {
    add: API_URL + "sanction/add",
    update: API_URL + "sanction/update",
    list: API_URL + "sanction/list",
    get: API_URL + "sanction/get",
  },
  employeeworkhistory: {
    add: API_URL + "employeeworkhistory/add",
    update: API_URL + "employeeworkhistory/update",
    list: API_URL + "employeeworkhistory/list",
    get: API_URL + "employeeworkhistory/get",
    getbyempid: API_URL + "employeeworkhistory/getbyempid/",
  },
  bulkupload: {
    add: API_URL + "bulkupload/add",
    update: API_URL + "bulkupload/update",
    list: API_URL + "bulkupload/list",
    get: API_URL + "bulkupload/get",
    getbyempid: API_URL + "bulkupload/getbyempid/",
  },
  healthinsuranceprovider: {
    add: API_URL + "healthinsuranceprovider/add",
    update: API_URL + "healthinsuranceprovider/update",
    list: API_URL + "healthinsuranceprovider/list",
    get: API_URL + "healthinsuranceprovider/get",
  },
  identification: {
    add: API_URL + "identification/add",
    update: API_URL + "identification/update",
    list: API_URL + "identification/list",
    get: API_URL + "identification/get",
  },
  pensionprovider: {
    add: API_URL + "pensionprovider/add",
    update: API_URL + "pensionprovider/update",
    list: API_URL + "pensionprovider/list",
    get: API_URL + "pensionprovider/get",
  },
};
