import { API_URL } from "../services/app-config";

export let recruitmentUrl = {
  applicantcv: {
    add: API_URL + "applicantcv/add",
    update: API_URL + "applicantcv/update",
    list: API_URL + "applicantcv/list",
    get: API_URL + "applicantcv/get",
  },
  applicants: {
    add: API_URL + "applicants/add",
    update: API_URL + "applicants/update",
    list: API_URL + "applicants/list",
    get: API_URL + "applicants/get/",
  },
  contracttype: {
    add: API_URL + "contracttype/add",
    update: API_URL + "contracttype/update",
    list: API_URL + "contracttype/list",
    get: API_URL + "contracttype/get",
  },
  employmenttype: {
    add: API_URL + "employmenttype/add",
    update: API_URL + "employmenttype/update",
    list: API_URL + "employmenttype/list",
    get: API_URL + "employmenttype/get",
  },
  experiencelevel: {
    add: API_URL + "experiencelevel/add",
    update: API_URL + "experiencelevel/update",
    list: API_URL + "experiencelevel/list",
    get: API_URL + "experiencelevel/get",
  },
  jobapplication: {
    add: API_URL + "jobapplication/add",
    update: API_URL + "jobapplication/update",
    list: API_URL + "jobapplication/list",
    jobApplications: API_URL + "jobapplication/jobApplications",
    get: API_URL + "jobapplication/get",
  },
  jobinterview: {
    add: API_URL + "jobinterview/add",
    update: API_URL + "jobinterview/update",
    list: API_URL + "jobinterview/list",
    get: API_URL + "jobinterview/get",
  },
  jobinterviewdetail: {
    add: API_URL + "jobinterviewdetail/add",
    update: API_URL + "jobinterviewdetail/update",
    list: API_URL + "jobinterviewdetail/list",
    get: API_URL + "jobinterviewdetail/get",
    jobOfferBin: API_URL + "jobinterviewdetail/jobOfferBin",
    jobOfferBin2: API_URL + "jobinterviewdetail/jobOfferBin2",
    notRecommended: API_URL + "jobinterviewdetail/notRecommended",
    jobinterviewDetailHistory: API_URL + "jobinterviewdetail/jobinterviewDetailHistory",
  },
  joboffer: {
    add: API_URL + "joboffer/add",
    update: API_URL + "joboffer/update",
    list: API_URL + "joboffer/list",
    get: API_URL + "joboffer/get",
    sendOfferLetter: API_URL + "joboffer/sendOfferLetter",
  },
  jobshortlist: {
    add: API_URL + "jobshortlist/add",
    update: API_URL + "jobshortlist/update",
    list: API_URL + "jobshortlist/list",
    get: API_URL + "jobshortlist/get",
  },
  jobshortlistdetail: {
    add: API_URL + "jobshortlistdetail/add",
    update: API_URL + "jobshortlistdetail/update",
    list: API_URL + "jobshortlistdetail/list",
    get: API_URL + "jobshortlistdetail/get",
    jobShortlistDetailHistory: API_URL + "jobshortlistdetail/jobShortlistDetailHistory",
  },
  recruitmentstage: {
    add: API_URL + "recruitmentstage/add",
    update: API_URL + "recruitmentstage/update",
    list: API_URL + "recruitmentstage/list",
    get: API_URL + "recruitmentstage/get",
  },
  recruitmentstatus: {
    add: API_URL + "recruitmentstatus/add",
    update: API_URL + "recruitmentstatus/update",
    list: API_URL + "recruitmentstatus/list",
    get: API_URL + "recruitmentstatus/get",
  },
  vacancy: {
    add: API_URL + "vacancy/add",
    update: API_URL + "vacancy/update",
    list: API_URL + "vacancy/list2",
    get: API_URL + "vacancy/get/",
    dashboard: API_URL + "vacancy/dashboard",
  },
  skills: {
    add: API_URL + "skills/add",
    update: API_URL + "skills/update",
    list: API_URL + "skills/list",
    get: API_URL + "skills/get",
  },
  yearsofexperience: {
    add: API_URL + "yearsofexperience/add",
    update: API_URL + "yearsofexperience/update",
    list: API_URL + "yearsofexperience/list",
    get: API_URL + "yearsofexperience/get",
  },
  professions: {
    add: API_URL + "professions/add",
    update: API_URL + "professions/update",
    list: API_URL + "professions/list",
    get: API_URL + "professions/get",
  },
  professiongroup: {
    add: API_URL + "professiongroup/add",
    update: API_URL + "professiongroup/update",
    list: API_URL + "professiongroup/list",
    get: API_URL + "professiongroup/get",
  },
};
