import { API_URL } from '../services/app-config';

export let projectUrl = {
    milestonemonitoring: {
        add: API_URL + 'milestonemonitoring/add',
        update: API_URL + 'milestonemonitoring/update',
        list: API_URL + 'milestonemonitoring/list',
        get: API_URL + 'milestonemonitoring/get',
    },
    project: {
        add: API_URL + 'project/add',
        update: API_URL + 'project/update',
        list: API_URL + 'project/list',
        get: API_URL + 'project/get/',
    },
    projectdocumentupload: {
        add: API_URL + 'projectdocumentupload/add',
        update: API_URL + 'projectdocumentupload/update',
        list: API_URL + 'projectdocumentupload/list',
        get: API_URL + 'projectdocumentupload/get',
    },
    projectexpense: {
        add: API_URL + 'projectexpense/add',
        update: API_URL + 'projectexpense/update',
        list: API_URL + 'projectexpense/list',
        get: API_URL + 'projectexpense/get',
    },
    projectmanager: {
        add: API_URL + 'projectmanager/add',
        update: API_URL + 'projectmanager/update',
        list: API_URL + 'projectmanager/list',
        get: API_URL + 'projectmanager/get',
    },
    projectmilestone: {
        add: API_URL + 'projectmilestone/add',
        update: API_URL + 'projectmilestone/update',
        list: API_URL + 'projectmilestone/list',
        get: API_URL + 'projectmilestone/get/',
        projectMilestonesByProjectId: API_URL + 'projectmilestone/projectMilestonesByProjectId/',
    },
    projectreview: {
        add: API_URL + 'projectreview/add',
        update: API_URL + 'projectreview/update',
        list: API_URL + 'projectreview/list',
        get: API_URL + 'projectreview/get',
    },
    projectreviewplan: {
        add: API_URL + 'projectreviewplan/add',
        update: API_URL + 'projectreviewplan/update',
        list: API_URL + 'projectreviewplan/list',
        get: API_URL + 'projectreviewplan/get',
    },
    projectrisk: {
        add: API_URL + 'projectrisk/add',
        update: API_URL + 'projectrisk/update',
        list: API_URL + 'projectrisk/list',
        get: API_URL + 'projectrisk/get/',
        projectRisksByID: API_URL + 'projectrisk/projectRisksByID/',
    },
    projectstatus: {
        add: API_URL + 'projectstatus/add',
        update: API_URL + 'projectstatus/update',
        list: API_URL + 'projectstatus/list',
        get: API_URL + 'projectstatus/get',
    },
    projectsubtype: {
        add: API_URL + 'projectsubtype/add',
        update: API_URL + 'projectsubtype/update',
        list: API_URL + 'projectsubtype/list',
        get: API_URL + 'projectsubtype/get',
    },
    projecttask: {
        add: API_URL + 'projecttask/add',
        update: API_URL + 'projecttask/update',
        list: API_URL + 'projecttask/list',
        get: API_URL + 'projecttask/get/',
        projectTasksByProjectID: API_URL + 'projecttask/projectTasksByProjectID/',
    },
    projectteam: {
        add: API_URL + 'projectteam/add',
        update: API_URL + 'projectteam/update',
        list: API_URL + 'projectteam/list',
        get: API_URL + 'projectteam/get/',
        projectTeamByProjectID: API_URL + 'projectteam/projectTeamByProjectID/',
    },
    projecttool: {
        add: API_URL + 'projecttool/add',
        update: API_URL + 'projecttool/update',
        list: API_URL + 'projecttool/list',
        get: API_URL + 'projecttool/get/',
        projectToolsByProjectID: API_URL + 'projecttool/projectToolsByProjectID/',
    },
    projecttype: {
        add: API_URL + 'projecttype/add',
        update: API_URL + 'projecttype/update',
        list: API_URL + 'projecttype/list',
        get: API_URL + 'projecttype/get',
    },
    risk: {
        add: API_URL + 'risk/add',
        update: API_URL + 'risk/update',
        list: API_URL + 'risk/list',
        get: API_URL + 'risk/get',
    },
    riskmitigant: {
        add: API_URL + 'riskmitigant/add',
        update: API_URL + 'riskmitigant/update',
        list: API_URL + 'riskmitigant/list',
        get: API_URL + 'riskmitigant/get/',
    },
    projectcategory: {
        add: API_URL + '.projectcategory/add',
        update: API_URL + '.projectcategory/update',
        list: API_URL + '.projectcategory/list',
        get: API_URL + '.projectcategory/get/',
    },
    projectsub: {
        add: API_URL + 'projectsub/add',
        update: API_URL + 'projectsub/update',
        list: API_URL + 'projectsub/list',
        get: API_URL + 'projectsub/get/',
        subProjectsByProjectId: API_URL + 'projectsub/subProjectsByProjectId/',
        subProjectsBySubProjectId: API_URL + 'projectsub/subProjectsBySubProjectId/',
    },
    projectsubcategory: {
        add: API_URL + 'projectsubcategory/add',
        update: API_URL + 'projectsubcategory/update',
        list: API_URL + 'projectsubcategory/list',
        get: API_URL + 'projectsubcategory/get/',
    },
    projectteamreassignment: {
        add: API_URL + 'projectteamreassignment/add',
        update: API_URL + 'projectteamreassignment/update',
        list: API_URL + 'projectteamreassignment/list',
        get: API_URL + 'projectteamreassignment/get/',
    },
};
